apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: amq-rmendes
  namespace: amq
spec:
  acceptors:
    - name: custom
      port: 5672
      protocols: 'amqp,openwire'
  addressSettings:
    addressSetting:
      - deadLetterAddress: dla
        match: amqp*
    applyRule: merge_all
  console:
    expose: true
  deploymentPlan:
    size: 2
    persistenceEnabled: true
    requireLogin: true
    messageMigration: true
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder
    storage:
      size: 5Gi

